### PR TITLE
Upgrade to Spring Security 4.0

### PR DESCRIPTION
**Pull request by gschlager**

### CODE REVIEW

**Comment by orzeh** [comment]
+1

**Comment by awhitford** [comment]
+1

This looks like it addresses [FLEX-240](https://jira.spring.io/browse/FLEX-240).

**Comment by tornaia** [comment]
+1

**Comment by roded** [comment]
+1

**Comment by Dretch** [comment]
+1

**Comment by roberthunt** [comment]
+1

**Comment by guruscott-meyer** [comment]
What's the status of this PR?  The upgrade to FLEX-240 is essential to a project I'm currently working on.

**Comment by sdeleuze** [comment]
Hey sorry for the lag, but this project is not active anymore.

I see no issue to integrate this contribution in master but:
 - be aware that no release is planned
 - tests seems broken when applying these changes

**Pull request closed without merging**
